### ISSUE TITLE
Starting point to install

### ISSUE THREAD

**Issue by MasterSkepticista** [gpgreen/livingstone2#1]
What are the dependencies to build this/run this? 
32bit/64bit ?
How to run stanley?
Any starting point on how to just install it?

**Comment by gpgreen** [comment]
There are a number of dependencies, which the configure scripts will look for. I have forked Mico to build on a more modern linux as this very old version. A bigger problem is that NASA didn't release a library that is used in the code to make it functional. I stopped at that point. It might be worth asking them if they are going to release it.

**Comment by MasterSkepticista** [comment]
> There are a number of dependencies, which the configure scripts will look for. I have forked Mico to build on a more modern linux as this very old version. A bigger problem is that NASA didn't release a library that is used in the code to make it functional. I stopped at that point. It might be worth asking them if they are going to release it.

I'm stuck at installing combat. I compiled everything, but this one thing remains. It is used in Stanley. Any ideas on how to install combat? It basically needs the ORB, which means, maybe mico isn't installed. Are we on the same page?

It shows me error at the point
'package require combat'

in a .tcl file, which I don't remember at the moment.

**Comment by gpgreen** [comment]
Mico is required. I thnk that combat is the tcl bindings to CORBA, and mico is the CORBA implementation they were using. I have this repo if you want to try 
https://github.com/gpgreen/mico

**Comment by MasterSkepticista** [comment]
> Mico is required. I thnk that combat is the tcl bindings to CORBA, and mico is the CORBA implementation they were using. I have this repo if you want to try
> https://github.com/gpgreen/mico

Okay, that worked for the install process. Can you tell me what output did you get while running ./runtests cb in l2-regress? Mine seems to get stuck, CPU being used, showing only 'Testing cb5.0-1000' and it doesn't proceed. Even Oliver crashes due to Java SIGSEGV error.

**Comment by gpgreen** [comment]
I don't remember getting segv errors. Are you using openjdk or oracle java? Did you try to run any of the other binaries?

I cannot check my build as i had a hard drive failure that wiped my build directory for this project.

**Comment by MasterSkepticista** [comment]
I built Stanley using Oracle’s 1.6.0_43, and run it with that same, which works. But for oliver, it required JDK1.4.* So I installed JDK1.4.2_12 alongside also for oliver, which gives SIGSEGV error (when I try to Run, post compilation, of any model in Oliver)
(Both are Oracle JDKs)

I can get away with not using oliver because Stanley works. Just one help I need. When I build model and run with Stanley, it gets stuck at ‘Please wait while Livingstone processes command…’ in the Stanley GUI. It gave no build errors while making L2-tools, nor does it give any errors in terminal while running. Any suggestions?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gpgreen** [comment]
There is a library that is needed, that NASA didn't release. I am going from memory from 2 years ago. I believe the library is a TCL library, so there should be either an error/warning during build that it is missing, or during load of stanley. Without that library, the sw isn't going to do what it is supposed to do. This is why i stopped working on it. I didn't make a note of which library it was. Conceivably we could ask NASA to release it also. I had looked at some of the call sites, and it didn't seem easy to recreate it.

**Comment by MasterSkepticista** [comment]
It seems that SIGSEGV error is prevalent on all JDKs, even on 1.8.0_74 (8u74), can get away with that.
I found one text file which explained how to create a RELEASE package. In that section is a text which writes:

./configure –enable-l2run –enable-l2-strip
In mba/cpp RELEASE.txt

L2run executable is needed, maybe?

But, NASA’s online package, when configured with these args shows that it doesn’t exist
‘no such argument –enable-l2run –enable-l2-strip’
Did they remove these in the last build?
Any ideas on that?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gpgreen** [comment]
I don't really have much idea. Need to ask for help from NASA.

**Comment by MasterSkepticista** [comment]
Alright, thanks for all till now! I'll let you know if it goes well!😄

On Sun, Jul 28, 2019, 12:09 AM Greg Green <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't really have much idea. Need to ask for help from NASA.

**Comment by MasterSkepticista** [comment]
Hey greg. I am getting a clearer picture with every file and errors I'm encountering now. I know you might not be able to help me with those files. But maybe you remember what worked for you or what not.

I start ./l2tools commandline interface, and when I create a "newEngine CBFS <params list>", I then run "refresh" command, which simply refreshes the state (for Stanley UI if it is active, so basically it does nothing to the engine itself). I get "No L2 Engine running" response. Confirmed from multiple tests that L2 engine isn't working. Didn't get any build/make errors. What could it be?

Or put it differently, how can I get the ONLY L2 engine commandline working with this package you have on GitHub? No stanley, nothing. Just L2 engine.

**Comment by MasterSkepticista** [comment]
Got all working! Thanks! It runs on Windows 10
